spring:
  application:
    name: bank_rest
  datasource:
    url: jdbc:postgresql://localhost:5433/bank_db
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: true
    change-log: classpath:db/migration/changelog-master.yaml
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
  docker:
    compose:
      enabled: true
      file: docker-compose.yml
jwt:
  secret: "ZmQ0ZGI5NjQ0MDQwY2I4MjMxY2Y3ZmI3MjdhN2ZmMjNhODViOTg1ZGE0NTBjMGM4NDA5NzYxMjdjOWMwYWRmZAo="
  expiration: 86400000
springdoc:
  model-and-view-allowed: true
  default-produces-media-type: application/json